# Generated by Django 3.2.12 on 2023-10-14 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_alter_profile_signature_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='Amount',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='profile',
            name='manual_signature_image',
            field=models.CharField(max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='signature_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
