# Generated by Django 3.2.12 on 2023-10-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_auto_20231015_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='total_amount',
            field=models.FloatField(default=0),
        ),
    ]
