# Generated by Django 3.2.12 on 2023-10-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_receipt_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='total_amount',
            field=models.FloatField(default=0, null=True),
        ),
    ]
