# Generated by Django 3.2.12 on 2023-10-17 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_emailaddress_idx_upper_email'),
        ('webapp', '0013_alter_receipt_total_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomEmailAddress',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('account.emailaddress',),
        ),
    ]
