# Generated by Django 3.2.12 on 2023-10-17 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_customemailaddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomEmailAddress',
        ),
    ]
