# Generated by Django 3.2.12 on 2023-10-18 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_auto_20231017_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
