# Generated by Django 3.2.12 on 2023-10-18 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_profile_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='logo_image',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='signature_image',
            field=models.TextField(null=True),
        ),
    ]
